[pytest]
pythonpath = . "Multimodal classifier" "Multimodal classifier/models/ecg models" "Multimodal classifier/data/Ecg data" "Multimodal classifier/losses" "Multimodal classifier/training/ecg training"
